using System;
using System.Collections.Generic;
using System.Linq;
using Sungero.Company;
using Sungero.Core;
using Sungero.CoreEntities;
using DirRX.HRLite.HRAcquaintanceAssignment;

namespace DirRX.HRLite
{
  partial class HRAcquaintanceAssignmentServerHandlers
  {

    public override void BeforeComplete(Sungero.Workflow.Server.BeforeCompleteEventArgs e)
    {
      var documents = _obj.DocumentGroup.InternalDocumentBases.Concat(_obj.AddendaGroup.InternalDocumentBases).ToList();
      
      // При выполнении задания с результатом "Подписать" проверить, что на документах есть согласующая подпись исполнителя задания.
      if (_obj.Result.Value == EmployeeSignAssignment.Result.Sign)
      {
        foreach (var document in documents)
        {
          var hasApprovalSignatures = Signatures.Get(document.LastVersion).Any(x => x.SignatureType == SignatureType.Endorsing && x.SignatoryFullName == _obj.Performer.Name);
          if (!hasApprovalSignatures && !Functions.Module.IsUserInTestRole())
            e.AddError(HRAcquaintanceAssignments.Resources.NeedEndorsingSignatureFormat(document.Name));
        }
        
        // Обновить свзяки документов с сотрудником.
        Functions.Module.CreateOrUpdateEmployeeDocumentLink(Employees.As(_obj.Performer), documents, DirRX.HRLite.EmployeeDocumentLink.Status.Signed);
      }
      
      // При выполнении задания с результатом "Отказать" проверить, что в тексте задания указана причина отказа.
      if (_obj.Result.Value == EmployeeSignAssignment.Result.Refuse)
      {
        if (_obj.Texts.Last().IsAutoGenerated.Value)
          e.AddError(HRAcquaintanceTasks.Resources.ErrorTextRefuseNoActiveText);
        
        // Обновить свзяки документов с сотрудником.
        Functions.Module.CreateOrUpdateEmployeeDocumentLink(Employees.As(_obj.Performer), documents, DirRX.HRLite.EmployeeDocumentLink.Status.Closed);
      }
    }

    public override void Created(Sungero.Domain.CreatedEventArgs e)
    {
      _obj.SignatureType = SignatureType.Endorsing.ToString();
    }
  }

}